Repository valudio/ui, pull requests merged in 2019-12, with the labels that each got.

#7 update gh-pages release action
  .github/workflows/release.yml
Labels: CI/CD

#9 compile ts before publish
  .gitignore
  .npmignore
  dist.tsconfig.json
  package.json
Labels: CI/CD

#10 Added input type prop + Input type password story
  src/Input/index.tsx
  src/Input/stories.tsx
Labels: enhancement

#11 version bump
  package.json
Labels: bug

#12 Updated input styles
  package-lock.json
  package.json
  src/Input/styles.ts
Labels: enhancement

#13 Feature/theme
  README.md
  package.json
  src/Button/stories.tsx
  src/Button/styles.ts
  src/Input/styles.ts
  src/Input/test.tsx
  src/components/Button/index.tsx
  src/components/Button/stories.tsx
  src/components/Button/styles.ts
  src/components/Button/test.tsx
  src/components/Input/index.tsx
  src/components/Input/stories.tsx
  src/components/Input/styles.ts
  src/components/Input/test.tsx
  src/components/Provider/index.tsx
  src/default-theme.ts
  src/index.ts
  src/models/index.ts
  src/models/theme.ts
  yarn.lock
Labels: enhancement

#18 deploy gh-pages working
  .github/workflows/release.yml
  package.json
Labels: CI/CD

#21 Added Spinner component
  package.json
  src/components/Spinner/index.tsx
  src/components/Spinner/stories.tsx
  src/components/Spinner/styles.ts
  src/components/Spinner/test.tsx
Labels: enhancement

#23 Version bump
  package.json
Labels: CI/CD

#26 Fixed component export members
  package.json
  src/index.ts
Labels: bug

#27 Fixed MultiSelect horizontal visibility + onChange selected items
  package.json
  src/components/MultiSelect/index.tsx
  src/components/MultiSelect/styles.ts
  src/components/MultiSelect/test.tsx
  src/models/option.ts
Labels: bug

#29 Feature/icons
  babel.config.js
  package.json
  src/assets/fonts/icons.ttf
  src/assets/fonts/synlab.ttf
  src/components/Icon/index.tsx
  src/components/Icon/stories.tsx
  src/components/Icon/styles.ts
  src/components/Icon/text.tsx
  src/components/Provider/index.tsx
  src/components/Table/HeaderCell/index.tsx
  src/components/Table/HeaderCell/styles.ts
  src/global-style.ts
  src/models/icon-name.ts
  src/models/index.ts
  src/models/table-column.ts
  src/typings.d.ts
  yarn.lock
Labels: enhancement

#30 Fixed components export + MultiSelect visibility issue
  package-lock.json
  package.json
  src/components/Checkbox/index.tsx
  src/components/Checkbox/styles.ts
  src/components/MultiSelect/index.tsx
  src/components/MultiSelect/styles.ts
  src/index.ts
Labels: bug

#31 Added test action file
  package-lock.json
  package.json
  yarn.lock
Labels: CI/CD, bug

#32 Version bump
  package.json
Labels: CI/CD

#33 Fixed icons font files copy on publish step
  package-lock.json
  package.json
  src/assets/fonts/synlab.ttf
  yarn.lock
Labels: bug

#34 Checkbox code refactor
  package.json
  src/components/Checkbox/index.tsx
  src/components/Checkbox/styles.ts
Labels: enhancement

#35 Fallback message added to Table
  package.json
  src/components/Table/index.tsx
  src/components/Table/stories.tsx
  src/components/Table/styles.ts
  src/default-theme.ts
  src/models/theme.ts
Labels: enhancement

#36 Fix/export File component + CSS issue
  package.json
  src/components/MultiSelect/styles.ts
  src/index.ts
Labels: bug

#37 Addes style base property + StatusDot custom color
  package.json
  src/components/StatusDot/index.tsx
  src/components/StatusDot/stories.tsx
  src/models/base-props.ts
Labels: enhancement

#39 File icons added
  .storybook/styles.css
  package.json
  src/assets/fonts/icons.ttf
  src/components/File/index.tsx
  src/components/File/stories.tsx
  src/components/File/styles.ts
  src/components/Icon/stories.tsx
  src/components/Icon/styles.ts
  src/components/Table/stories.tsx
  src/models/file-type.ts
  src/models/icon-name.ts
Labels: enhancement

#40 MultiSelect reworked
  .storybook/styles.css
  README.md
  dist.tsconfig.json
  src/components/Button/index.tsx
  src/components/Checkbox/index.tsx
  src/components/File/index.tsx
  src/components/Icon/index.tsx
  src/components/Input/index.tsx
  src/components/Label/index.tsx
  src/components/MultiSelect/Dropdown/index.tsx
  src/components/MultiSelect/Dropdown/styles.ts
  src/components/MultiSelect/Item.tsx
  src/components/MultiSelect/Item/index.tsx
  src/components/MultiSelect/Item/styles.ts
  src/components/MultiSelect/index.tsx
  src/components/MultiSelect/stories.tsx
  src/components/MultiSelect/styles.ts
  src/components/MultiSelect/test.tsx
  src/components/Spinner/index.tsx
  src/components/Table/index.tsx
  src/components/Table/stories.tsx
  src/helpers/dom.ts
  src/models/option.ts
Labels: enhancement

#42 Version bump
  package.json
Labels: bug

#43 fix test wrongly named
  src/components/Icon/test.tsx
Labels: bug

#45 Feature pagination
  src/components/File/stories.tsx
  src/components/Icon/index.tsx
  src/components/Label/stories.tsx
  src/components/MultiSelect/stories.tsx
  src/components/Pagination/Page/index.tsx
  src/components/Pagination/Page/styles.ts
  src/components/Pagination/index.tsx
  src/components/Pagination/stories.tsx
  src/components/Pagination/styles.ts
  src/components/Pagination/test.tsx
  src/components/Spinner/stories.tsx
Labels: enhancement

#47 fix multiselect details
  package.json
  src/components/Bubble/index.tsx
  src/components/Bubble/stories.tsx
  src/components/Bubble/styles.ts
  src/components/Bubble/test.tsx
  src/components/MultiSelect/Dropdown/styles.ts
  src/components/MultiSelect/Item/styles.ts
  src/components/MultiSelect/index.tsx
  src/components/MultiSelect/styles.ts
  src/index.ts
  src/models/option.ts
Labels: bug

#50 Toggle component added
  package.json
  src/components/Checkbox/index.tsx
  src/components/MultiSelect/Item/index.tsx
  src/components/Toggle/index.tsx
  src/components/Toggle/stories.tsx
  src/components/Toggle/styles.ts
  src/components/Toggle/test.tsx
  src/index.ts
Labels: enhancement

#51 Fix/minor issues
  package.json
  src/components/MultiSelect/index.tsx
  src/components/MultiSelect/stories.tsx
  src/components/Pagination/index.tsx
Labels: bug

#52 Modal implemented
  src/components/Bubble/stories.tsx
  src/components/File/styles.ts
  src/components/Modal/index.tsx
  src/components/Modal/stories.tsx
  src/components/Modal/styles.ts
  src/components/Modal/test.tsx
  src/index.ts
Labels: enhancement

#53 Version bump
  package.json
Labels: CI/CD

#55 Added isHidden property on table column
  package.json
  src/components/Table/HeaderCell/index.tsx
  src/components/Table/Row/index.tsx
  src/components/Table/stories.tsx
  src/models/table-column.ts
Labels: enhancement

#56 click on file implemented
  package.json
  src/components/File/index.tsx
Labels: enhancement

#57 file disabled implementation
  package.json
  src/components/File/index.tsx
  src/components/File/stories.tsx
  src/components/File/styles.ts
Labels: enhancement

#58 minor tweaks
  .storybook/styles.css
  package.json
  src/components/Icon/index.tsx
  src/components/Icon/stories.tsx
  src/components/Icon/styles.ts
  src/components/Modal/styles.ts
Labels: bug, enhancement

#60 Custom style on table row
  .storybook/styles.css
  package.json
  src/components/Table/Row/index.tsx
  src/models/table-column.ts
  src/typings.d.ts
Labels: enhancement

#61 fix size property access
  src/components/Table/HeaderCell/index.tsx
Labels: bug

#62 fix row not aplying column styles
  package.json
  src/components/Table/Row/index.tsx
Labels: bug

#63 z-index fixed
  package.json
  src/components/Modal/styles.ts
Labels: bug

#64 Feature/menu
  .storybook/styles.css
  package.json
  src/components/Icon/stories.tsx
  src/components/Input/stories.tsx
  src/components/Menu/LanguageItem/index.tsx
  src/components/Menu/LanguageItem/styles.ts
  src/components/Menu/MenuItem/index.tsx
  src/components/Menu/MenuItem/styles.ts
  src/components/Menu/index.tsx
  src/components/Menu/stories.tsx
  src/components/Menu/styles.ts
  src/components/Menu/test.tsx
  src/index.ts
  src/models/index.ts
  src/models/menu-item.ts
Labels: enhancement

#65 fix checkbox not updating its value
  src/components/Checkbox/index.tsx
  src/components/Modal/index.tsx
  src/components/MultiSelect/Item/index.tsx
Labels: bug

#66 version bump
  package.json
Labels: bug

#67 menu is now fixed
  .storybook/styles.css
  package.json
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
Labels: enhancement

#68 Added MenuItem to export members
  package.json
  src/index.ts
Labels: bug

#69 Added locale language support to LanguageItem menu
  package.json
  src/components/Menu/LanguageItem/index.tsx
  src/components/Menu/index.tsx
  src/components/Menu/stories.tsx
  src/models/index.ts
  src/models/language.ts
Labels: enhancement

#70 Datetime component added
  .storybook/styles.css
  package.json
  src/components/DateTime/index.tsx
  src/components/DateTime/stories.tsx
  src/components/DateTime/styles.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#71 Icons update
  package.json
  src/assets/fonts/icons.ttf
  src/components/Icon/stories.tsx
  src/components/Icon/styles.ts
  src/models/icon-name.ts
Labels: enhancement

#75 modal overflow and click on overlay
  package.json
  src/components/Modal/index.tsx
  src/components/Modal/stories.tsx
  src/components/Modal/styles.ts
Labels: bug

#76 Fix/pagination
  package-lock.json
  package.json
  src/components/Icon/styles.ts
  src/components/Pagination/index.tsx
  src/components/Pagination/stories.tsx
Labels: bug

#77 Feature/menu logo
  package.json
  src/components/Menu/index.tsx
  src/components/Menu/stories.tsx
  src/components/Menu/styles.ts
Labels: enhancement

#78 menu logo
  src/components/Menu/styles.ts
Labels: enhancement
