Repository valudio/ui, pull requests merged in 2020-02, with the labels that each got.

#109 fix date input height
  package.json
  src/components/DateTime/styles.ts
Labels: bug

#110 Select implementation
  package.json
  src/components/Modal/index.tsx
  src/components/MultiSelect/index.tsx
  src/components/Select/Dropdown/index.tsx
  src/components/Select/Dropdown/styles.ts
  src/components/Select/Item/index.tsx
  src/components/Select/Item/styles.ts
  src/components/Select/index.tsx
  src/components/Select/stories.tsx
  src/components/Select/styles.ts
  src/components/Select/test.tsx
Labels: enhancement

#111 added to barrell and max height on select
  package.json
  src/components/Select/Dropdown/styles.ts
  src/index.ts
Labels: enhancement

#112 fix modal customization
  package.json
  src/components/Modal/index.tsx
Labels: bug

#113 input and select initial value option
  package.json
  src/components/Input/index.tsx
  src/components/Input/stories.tsx
  src/components/Select/index.tsx
  src/components/Select/stories.tsx
Labels: enhancement

#114 modal container flex and fix select open event
  package.json
  src/components/Modal/stories.tsx
  src/components/Modal/styles.ts
  src/helpers/dom.ts
Labels: bug

#115 title implementation
  package.json
  src/components/Button/stories.tsx
  src/components/Button/styles.ts
  src/components/Title/index.tsx
  src/components/Title/stories.tsx
  src/components/Title/styles.ts
  src/components/Title/test.tsx
  src/index.ts
Labels: enhancement

#116 align design
  package.json
  src/components/Button/styles.ts
  src/components/Table/HeaderCell/styles.ts
  src/components/Table/Row/styles.ts
Labels: enhancement

#117 Updated icon font
  package-lock.json
  package.json
  src/assets/fonts/icons.ttf
  src/components/Icon/stories.tsx
  src/components/Icon/styles.ts
  src/models/icon-name.ts
Labels: enhancement

#118 Circular button implementation
  package.json
  src/components/Button/index.tsx
  src/components/Button/stories.tsx
  src/components/Button/styles.ts
Labels: enhancement

#119 fix button size
  package.json
  src/components/Button/styles.ts
Labels: bug

#120 Tertiary button style implementation
  package.json
  src/components/Button/index.tsx
  src/components/Button/stories.tsx
  src/components/Button/styles.ts
  src/components/Menu/styles.ts
Labels: enhancement

#121 Added jsx addon
  .storybook/addons.js
  .storybook/config.ts
  package.json
  src/components/Bubble/stories.tsx
  src/components/Button/stories.tsx
  src/components/Checkbox/stories.tsx
  src/components/DateTime/stories.tsx
  src/components/Field/stories.tsx
  src/components/File/stories.tsx
  src/components/Icon/stories.tsx
  src/components/Input/stories.tsx
  src/components/Menu/stories.tsx
  src/components/Modal/stories.tsx
  src/components/MultiSelect/stories.tsx
  src/components/Pagination/stories.tsx
  src/components/Select/stories.tsx
  src/components/SnackBar/stories.tsx
  src/components/Spinner/stories.tsx
  src/components/StatusDot/stories.tsx
  src/components/Table/stories.tsx
  src/components/Title/stories.tsx
  src/components/Toggle/stories.tsx
Labels: enhancement

#122 Feature/reset input (Externally reset input state)
  README.md
  dist.tsconfig.json
  package.json
  src/components/Checkbox/index.tsx
  src/components/Checkbox/stories.tsx
  src/components/DateTime/index.tsx
  src/components/Input/index.tsx
  src/components/MultiSelect/Item/index.tsx
  src/components/MultiSelect/index.tsx
  src/components/Select/index.tsx
  src/models/index.ts
  src/models/input-props.ts
  storybook.tsconfig.json
  yarn.lock
Labels: enhancement

#123 avoid button default type 'submit'
  package.json
  src/components/Button/index.tsx
Labels: bug

#125 Version bump
  package.json
Labels: bug

#20 Clean workflows
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: CI/CD

#126 table row clickable
  package.json
  src/components/Table/Row/index.tsx
  src/components/Table/index.tsx
  src/components/Table/stories.tsx
  src/models/index.ts
  src/models/table-item.ts
Labels: enhancement

#127 add row properties on table from items
  package.json
  src/components/Table/index.tsx
Labels: bug

#137 Print icon added
  package.json
  src/components/Icon/stories.tsx
  src/models/icon-name.ts
Labels: enhancement

#139 Updated icon font
  package-lock.json
  package.json
  src/assets/fonts/icons.ttf
  src/components/Icon/stories.tsx
  src/components/Icon/styles.ts
  src/models/icon-name.ts
Labels: enhancement

#140 Aligned font family on missing components
  package-lock.json
  package.json
  src/components/DateTime/styles.ts
  src/components/Input/styles.ts
Labels: bug

#141 🌐 Add months and week language literals
  package-lock.json
  package.json
  src/components/Bubble/stories.tsx
  src/components/Button/stories.tsx
  src/components/Checkbox/stories.tsx
  src/components/DateTime/index.tsx
  src/components/DateTime/stories.tsx
  src/components/File/stories.tsx
  src/components/Input/stories.tsx
  src/components/Modal/stories.tsx
  src/components/MultiSelect/stories.tsx
  src/components/Select/stories.tsx
  src/components/Toggle/stories.tsx
  src/literals.ts
Labels: bug, enhancement

#142 Add current month i18n to DateTime picker
  package-lock.json
  package.json
  src/components/DateTime/index.tsx
Labels: enhancement

#143 Force DateTime current month language
  package.json
  src/components/DateTime/index.tsx
  src/components/DateTime/stories.tsx
  src/literals.ts
Labels: bug

#144 Fix table row vertical alignment
  package.json
  src/components/Table/Row/styles.ts
Labels: bug

#145 Add active property to Menu items
  package.json
  src/components/Menu/MenuItem/index.tsx
  src/components/Menu/MenuItem/styles.ts
  src/components/Menu/stories.tsx
Labels: enhancement

#146 Menu bugfixes and enhancements
  package-lock.json
  package.json
  src/components/Menu/index.tsx
  src/components/Menu/stories.tsx
  src/components/Menu/styles.ts
Labels: bug, enhancement

#147 Fix build
  package.json
  src/components/Menu/index.tsx
Labels: bug

#148 Dowgrade styled-components and added as external dependency
  package-lock.json
  package.json
Labels: bug

#149 Fix menu logo container size
  package.json
  src/components/Menu/styles.ts
Labels: bug

#150 Bugfixing on Menu and DateTime picker
  package.json
  src/components/DateTime/index.tsx
  src/components/Menu/LanguageItem/index.tsx
  src/components/Menu/index.tsx
  src/components/Menu/stories.tsx
Labels: bug

#151 Fix input and select placeholder colour
  package.json
  src/components/Input/styles.ts
  src/components/Select/styles.ts
Labels: bug

#152 Fix multiselect bugs
  package.json
  src/components/Menu/LanguageItem/index.tsx
  src/components/Menu/index.tsx
  src/components/MultiSelect/index.tsx
  src/components/MultiSelect/styles.ts
  src/components/Select/index.tsx
Labels: bug

#154 Fix datetime current month change
  package-lock.json
  package.json
  src/components/MultiSelect/styles.ts
Labels: bug

#155 Fix DateTime placeholder color
  package.json
  src/components/DateTime/styles.ts
Labels: bug
